scan_filter_chain:
  - name: angular_bounds
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params:
      lower_angle: -3.0
      upper_angle: 3.0
  
  - name: range_filter
    type: laser_filters/LaserScanRangeFilter
    params:
      use_message_range_limits: false
      lower_threshold: 0.12
      upper_threshold: 10.0
      lower_replacement_value: -inf
      upper_replacement_value: inf
  
  - name: intensity_filter
    type: laser_filters/LaserScanIntensityFilter
    params:
      lower_threshold: 8000
      upper_threshold: 100000
      invert: true
  
  - name: shadows_filter
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 10.0
      max_angle: 170.0
      neighbors: 10
      window: 1
  
  - name: speckle_filter
    type: laser_filters/SpeckleFilter
    params:
      filter_type: 0
      max_range_difference: 0.1
      max_range: 10.0
      filter_window: 2
