custom_planner:
  ros__parameters:
    # 基本规划参数
    path_resolution: 0.05
    obstacle_clearance: 0.4    # 增加到0.4m以适应更宽的安全距离
    straight_line_preference: 1.5
    max_iterations: 20000
    
    # Ackermann参数
    min_turning_radius: 0.5
    is_ackermann: true
    
    # 机器人尺寸参数
    robot_width: 0.3           # 机器人宽度 (m)
    robot_length: 0.75         # 机器人长度 (m)
    inflation_radius: 0.4      # 障碍物膨胀半径 (m)
    
    # 调整A*搜索行为
    use_astar: true
    enable_path_smoothing: true
    
    # 高级参数
    path_simplification_max_length: 10
    path_simplification_min_angle: 0.2
    obstacle_inflation_radius: 0.3